### ISSUE TITLE
Allow to specify AWS region in appender configuration

### ISSUE THREAD

**Issue by vdenisov** [boxfuse/cloudwatchlogs-java-appender#5]
Right now, `CloudwatchLogsLog4J2Appender` doesn't accept AWS region from configuration, even though `CloudwatchLogsConfig` supports it, and it is referenced correctly in `CloudwatchLogsLogEventPutter`.

**Comment by axelfontaine** [comment]
This should be autodetected when running in a Boxfuse instance here: https://github.com/boxfuse/cloudwatchlogs-java-appender/blob/master/src/main/java/com/boxfuse/cloudwatchlogs/internal/CloudwatchLogsLogEventPutter.java#L54

Do you find it making the wrong choice for you? If yes, how so?

**Comment by vdenisov** [comment]
It works perfectly when running in AWS; and when running in local Boxfuse instance, I can easily fuse an environment variable, so it's not a problem as well. However, if running on a local machine, I have to not forget to set this variable in IDE's run configuration (or set an OS/user level environment variable) myself, and to explain this to all team members who're working with logging. It wasn't a problem until we started migrating all our codebase to use Markers and MDC to get better structured logs - having a way to just set it to a correct AWS region in `log4j2.xml` (which would then be shared with all team members) would've been nice.

If you're against exposing this config option, that's fine by me; if not - let me implement that (early next week seems likely) and send you a PR.

**Comment by axelfontaine** [comment]
Note that there is no need to set anything in a local Boxfuse instance as Boxfuse will automatically override the endpoint to point to a local CloudWatch Logs mock that is started by the Boxfuse Client. See https://github.com/boxfuse/cloudwatchlogs-java-appender/blob/master/src/main/java/com/boxfuse/cloudwatchlogs/CloudwatchLogsConfig.java#L21

Currently the appender auto-disables itself outside of a Boxfuse instance (due to the lack of `AWS_REGION` and `"BOXFUSE_CLOUDWATCHLOGS_ENDPOINT` environment variables). I assume this is not the behavior you want. Do you instead want it to log to

1. AWS CloudWatch Logs
2. a local CloudWatch Logs mock
3. stdout

?

**Comment by vdenisov** [comment]
TBH, I'd like it to log to wherever I can see the whole logged event (to make sure that all the fields are set correctly).

**Comment by axelfontaine** [comment]
The new `stdoutFallback` configuration property now enables outputting events to stdout in case no AWS region was detected.

**Comment by vdenisov** [comment]
Works very well, thanks a lot!
